site_name: OpenCDA
repo_url: https://github.com/xuhan417/OpenCDA-Documents
docs_dir: docs
theme: readthedocs
extra_css: [extra.css]

nav:
    - Home: index.md
    - Introduction: OpenCDA_introduction.md
    - Installation: OpenCDA_installation.md
    - Framework Structure: OpenCDA_structure.md
    - Examples: OpenCDA_examples.md
    - Benchmarks: OpenCDA_benchmark.md
    - Python API: python_api.md
    - About: about.md

